### ISSUE TITLE
synctex fails on ubuntu

### ISSUE THREAD

**Issue by flaport** [jupyterlab/jupyterlab-latex#88]
I have a similar issue as #78, however, I am on Ubuntu

jupyterlab v0.33.7
jupyterlab/latex v0.4.0

when I try to perform synctex from the editor to the pdf, i get the following error message:

```
[E 11:36:18.394 LabApp] Uncaught exception GET /latex/synctex/LATEX/icrc/main.tex?line=36&column=105&1533634578374 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/latex/synctex/LATEX/icrc/main.tex?line=36&column=105&1533634578374', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/flori/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/home/flori/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/home/flori/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
        yielded = self.gen.send(value)
      File "/home/flori/anaconda/lib/python3.6/site-packages/jupyterlab_latex/synctex.py", line 190, in get
        out = json.dumps(parse_synctex_response(out, pos))
      File "/home/flori/anaconda/lib/python3.6/site-packages/jupyterlab_latex/synctex.py", line 214, in parse_synctex_response
        raise Exception('Unable to parse SyncTeX response')
    Exception: Unable to parse SyncTeX response
[W 11:36:18.394 LabApp] Unhandled error
[E 11:36:18.395 LabApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0",
      "Accept": "*/*",
      "Accept-Language": "en-GB,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/lab",
      "Authorization": "token afef98a9e4bef8006e1a029c51aee570fd7cbcaf09da7289",
      "Content-Type": "application/json",
      "Origin": "http://localhost:8888",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1533634576|23:username-localhost-8888|44:ZDI3NDE3MTFhNTc1NDc3NWIxMjc5NDQ4ZDBmOTMwZWE=|c429fb2c2e3ad02e422b6f80bd5d247cbffcdbf9a05852376f39fa420cf17abf\"; _xsrf=2|9e21a47e|a267c52c66d22154bd876061f5360638|1533561997",
      "Connection": "keep-alive",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 11:36:18.395 LabApp] 500 GET /latex/synctex/LATEX/icrc/main.tex?line=36&column=105&1533634578374 (127.0.0.1) 4.63ms referer=http://localhost:8888/lab

```

And similarly from pdf to latex:
```
[E 11:37:15.488 LabApp] SyncTex command `synctex edit -o 2:0:0:main.pdf` errored with code: 255
[E 11:37:15.488 LabApp] Uncaught exception GET /latex/synctex/LATEX/icrc/main.pdf?page=2&x=0&y=0&1533634635471 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/latex/synctex/LATEX/icrc/main.pdf?page=2&x=0&y=0&1533634635471', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/flori/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/home/flori/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/home/flori/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
        yielded = self.gen.send(value)
      File "/home/flori/anaconda/lib/python3.6/site-packages/jupyterlab_latex/synctex.py", line 190, in get
        out = json.dumps(parse_synctex_response(out, pos))
      File "/home/flori/anaconda/lib/python3.6/site-packages/jupyterlab_latex/synctex.py", line 214, in parse_synctex_response
        raise Exception('Unable to parse SyncTeX response')
    Exception: Unable to parse SyncTeX response
[W 11:37:15.489 LabApp] Unhandled error
[E 11:37:15.489 LabApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0",
      "Accept": "*/*",
      "Accept-Language": "en-GB,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/lab",
      "Authorization": "token afef98a9e4bef8006e1a029c51aee570fd7cbcaf09da7289",
      "Content-Type": "application/json",
      "Origin": "http://localhost:8888",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1533634631|23:username-localhost-8888|44:NWJmNjJhODNlOWViNDJiZGI3N2RlYzIzNGIwMDFkODE=|e8ad8751d6e3c2ddb8211b2840eabb5dd0c28c08ee2d13338c7624ce5543daed\"; _xsrf=2|9e21a47e|a267c52c66d22154bd876061f5360638|1533561997",
      "Connection": "keep-alive",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 11:37:15.489 LabApp] 500 GET /latex/synctex/LATEX/icrc/main.pdf?page=2&x=0&y=0&1533634635471 (127.0.0.1) 4.93ms referer=http://localhost:8888/lab
```

My `.tex` files are compiled with `pdflatex` and I use `bibtex` for the bibliography. Also `synctex` is available in my path.

As a sidenote, synctex also works perfectly with the Latex Workshop extension of vscode.

Any ideas to solve this problem?

**Comment by ian-r-rose** [comment]
Hi @flaport, it may be that SyncTeX is producing some output that our (relatively simple) parser cannot handle. A couple of questions:
1. Does SyncTeX work on the example `.tex` file that is in this repository?
2. If so, do you have a minimal example of a `.tex` file that fails for you?

**Comment by flaport** [comment]
@t-makaro , my version of synctex is 1.3
@ian-r-rose , synctex also does not seem to work for the `sample.tex` file in the jupyterlab-latex repository, yielding the same uncaught exception response.

**Comment by ian-r-rose** [comment]
@flaport I've published a new release (`jupyterlab_latex==0.4.0`) that should output more information on the notebook server logs if SyncTeX fails. If you get the chance, can you let me know what it shows upon error?

**Comment by flaport** [comment]
@ian-r-rose , this update seems to have solved the issue. Synctex now works exactly as expected! thanks :)

**Comment by ian-r-rose** [comment]
Great, thanks for checking @flaport! Closing as fixed.
